### PR TITLE
Update Cargo.toml add repository url

### PR DESCRIPTION
**Pull request by szabgab**
to make crates.io, rust-digger and other sites link to it

### CODE REVIEW

**Review by sebosp — APPROVED** [review]
Thank you!

**Comment by szabgab** [comment]
Thanks for accepting the PR. I am building the [Rust Digger](https://rust-digger.code-maven.com/) to locate such crates and then I'll use this to further analyze the project.

**Comment by sebosp** [comment]
Really cool! How can I follow-up the progression of your project? Do you provide updates on reddit/hacker-news ?

**Comment by szabgab** [comment]
You can follow the [git repo](https://github.com/szabgab/rust-digger) and I will write more news posts and try to get it into [This week in Rust](https://this-week-in-rust.org/), but actually it might be a good idea to post the news links to the Reddit and HN. I am just always worried of potential backlash for "self promotion".

**Pull request merged**
